{% set name = "olmocr" %}
{% set version = "0.1.76" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/olmocr-{{ version }}.tar.gz
  sha256: 2e2c62ed96b6b2c0137a076fc03ac27714e8e5228c78dee4da1a1fb3bd91572c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - img2pdf
    - pikepdf
    - python >={{ python_min }}
    - numpy <2.0.0,>=1.26.1
    - cached_path
    - smart_open
    - pypdf >=5.2.0
    - pypdfium2
    - cryptography
    - lingua-language-detector
    - pillow
    - ftfy
    - bleach
    - markdown2
    - filelock
    - orjson
    - requests
    - zstandard
    - boto3
    - httpx
    - pytorch >=2.7.0
    - transformers >=4.51.1
    - beaker-py

test:
  imports:
    - olmocr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/allenai/olmocr
  summary: "Toolkit for linearizing PDFs for LLM datasets/training"
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
